### ISSUE TITLE
Line endings can break script

### ISSUE THREAD

**Issue by fletcher** [zcohan/simba-symbolication#3]
I occasionally get crash reports emailed to me in various ways.  Through some trial and error, it seems that a <space-newline> at the end of lines, instead of just <newline>, breaks the script.  A simple regexp to clean up the crash report would improve the reliability of the script greatly.

Thanks for packaging this up!

**Comment by fletcher** [comment]
Just saw that my comments got munged...  Corrected version here:

> I occasionally get crash reports emailed to me in various ways.  Through some trial and error, it seems that a `<space-newline>` at the end of lines, instead of just `<newline>`, breaks the script.  A simple regexp to clean up the crash report would improve the reliability of the script greatly.
> 
> Thanks for packaging this up!

**Comment by zcohan** [comment]
This issue should be fixed in the latest build. It doesn't use the old script anymore.
